### ISSUE TITLE
Review of the Cafeteria App

### ISSUE THREAD

**Issue by pranav-surya** [Rajanayaki/Cafeteria_app#1]
Suggestions and comments

- params are used as such in controllers. advising use of permitted params and sanitisation
- code organisation
	- all logic is written as part of controllers. business logic can be reorganised to a service layer using modules and included in controllers.
	- model specific functions should be moved to model files.
- refactoring
	- methods can be refactored by restricting them to have limited functions. but since the app has limited functionalities its fine here i think
- Exception handling is not implemented
- Implementing caching with memcached will give an idea about its use when working in itildesk in future.
- All views are monolithic. Advising use of partials to make views more modular.

- Bugs in the Order items page. items not visible

**Comment by pranav-surya** [comment]
@Rajanayaki please consider the comments in the review. thanks.

**Comment by Rajanayaki** [comment]
@pranav-surya Thanks for the review . working on them.
